"""spelled address wrong

Revision ID: 11e19c6627aa
Revises: 5875f6e2f8bf
Create Date: 2023-12-19 21:16:25.974878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e19c6627aa'
down_revision = '5875f6e2f8bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.drop_column('adderess')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adderess', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
