"""fixed relationships

Revision ID: 5875f6e2f8bf
Revises: 2e814016c8c5
Create Date: 2023-12-19 13:02:54.749056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5875f6e2f8bf'
down_revision = '2e814016c8c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_apartments_tenant_name_tenants', type_='foreignkey')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint('fk_properties_owner_name_owners', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_properties_owner_name_owners', 'owners', ['owner_name'], ['name'])

    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_apartments_tenant_name_tenants', 'tenants', ['tenant_name'], ['name'])

    # ### end Alembic commands ###
